### ISSUE TITLE
Very low contrast on info box

### ISSUE THREAD

**Issue by spydon** [nylo-core/nylo.dev#5]
![image](https://github.com/user-attachments/assets/06655bd6-82eb-4df1-872a-686714ce4514)

**Comment by agordn52** [comment]
@spydon,

Thanks for highlighting this, I'll take a look

**Comment by agordn52** [comment]
All done 🪄 https://nylo.dev/docs/5.20.0

**Comment by spydon** [comment]
Super, thanks! 🥳
